trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
  
- script: |
    ## Download the latest CLI for Linux amd64
    curl https://api.endorlabs.com/download/latest/endorctl_linux_amd64 -o endorctl
    ## Verify the checksum of the binary
    echo "$(curl -s https://api.endorlabs.com/sha/latest/endorctl_linux_amd64)  endorctl" | sha256sum -c
    ## Modify the permissions of the binary to ensure it is executable
    chmod +x ./endorctl
    ./endorctl scan --api-key $(ENDOR_API_CREDENTIALS_KEY) --api-secret $(ENDOR_API_CREDENTIALS_SECRET) -n kriti-learn --as-default-branch --tools --dependencies --as-default-branch --detached-ref-name $(Build.SourceBranchName)
  continueOnError: true
  displayName: 'Endor install and scan'