name: Endor Labs Main Branch Check for Secrets and Vulns
on:
  push:
    branches: [ new_main ]
  workflow_dispatch:
jobs:
  scan:
    permissions:
      security-events: write 
      contents: read 
      actions: read
      id-token: write 
      issues: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'
    - name: Build Package
      run: mvn clean install
    - name: Endor Labs Scan Main
      uses: endorlabs/github-action@v1.1.7
      with:
        namespace: 'diamantis' 
        scan_dependencies: true
        scan_secrets: true
        pr: false
        log_verbose: true
        log_level: debug
        endorctl_version: v1.7.81
        endorctl_checksum: "bc76b8e0469cb2532cf64f8475ba40bba773ecea2afd3162aa837e95afc9a8a2"
        scan_summary_output_type: 'table'
        sarif_file: 'findings.sarif'
        additional_args: '--bypass-host-check'
    - name: Upload findings to github
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'findings.sarif'
